name: Publish nuget Api Client

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dotnet/EpochFlow.ApiClient
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

       - name: Setup .NET Core SDK 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Build and Package 6.0
        run: |
          dotnet restore
          dotnet build -c Release
          dotnet pack --configuration Release --output nupkg

      - name: Publish to NuGet 6.0
        run: |
          dotnet nuget push ./nupkg/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}

      - name: Setup .NET Core SDK 7.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - name: Build and Package 7.0
        run: |
          dotnet restore
          dotnet build -c Release
          dotnet pack --configuration Release --output nupkg

      - name: Publish to NuGet 7.0
        run: |
          dotnet nuget push ./nupkg/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}

      - name: Setup .NET Core SDK 8.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Build and Package 8.0
        run: |
          dotnet restore
          dotnet build -c Release
          dotnet pack --configuration Release --output nupkg

      - name: Publish to NuGet 8.0
        run: |
          dotnet nuget push ./nupkg/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}