name: Release CLI toolkit

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dotnet/EpochFlow.Toolkit
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Build and Package
        run: |
          dotnet restore
          dotnet build -c Release
          dotnet publish -c Release -r win-x64 --self-contained /p:PublishSingleFile=true

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/Release/net8.0/win-x64/publish/*
          tag_name: ${{ github.ref }}
          title: Release ${{ github.ref }}
